// Fake libllama for testing LocalLlamaProvider's control flow, RAII, and
// prefix-cache logic WITHOUT a real model or real llama.cpp build.
// This cannot validate actual inference quality or real GPU behavior —
// only that LocalLlamaProvider's own code (batch construction, KV-cache
// trim calls, sampler chain lifecycle, tokenize/detokenize round-trip,
// prefix-reuse decision logic) is structurally correct and doesn't
// crash, leak, or double-free.

#include "third_party/llama_api.h"
#include <cstring>
#include <cstdio>
#include <string>
#include <vector>
#include <map>

static int g_backend_init_count = 0;

struct llama_model    { std::string path; int n_gpu_layers; };
struct llama_context  { llama_model* model; uint32_t n_ctx; std::vector<llama_token> kv_tokens; };
struct llama_vocab    { int dummy; };
struct llama_sampler  { std::vector<llama_sampler*> chain; float temp = 1.0f; bool is_chain=false; int kind=0; };

static llama_vocab g_vocab_singleton;

extern "C" {

void llama_backend_init() { g_backend_init_count++; printf("[stub] backend_init (count=%d)\n", g_backend_init_count); }
void llama_backend_free() { g_backend_init_count--; printf("[stub] backend_free (count=%d)\n", g_backend_init_count); }

llama_model_params llama_model_default_params() {
    return {0, true, false};
}
llama_context_params llama_context_default_params() {
    return {4096, 512, 0, 0};
}

llama_model* llama_model_load_from_file(const char* path, llama_model_params params) {
    printf("[stub] loading model: %s (n_gpu_layers=%d)\n", path, params.n_gpu_layers);
    auto* m = new llama_model{path, params.n_gpu_layers};
    return m;
}
void llama_model_free(llama_model* model) {
    printf("[stub] freeing model: %s\n", model->path.c_str());
    delete model;
}

llama_context* llama_init_from_model(llama_model* model, llama_context_params params) {
    printf("[stub] creating context (n_ctx=%u)\n", params.n_ctx);
    auto* c = new llama_context{model, params.n_ctx, {}};
    return c;
}
void llama_free(llama_context* ctx) {
    printf("[stub] freeing context\n");
    delete ctx;
}

const llama_vocab* llama_model_get_vocab(const llama_model*) {
    return &g_vocab_singleton;
}

// Fake tokenizer: one token per whitespace-separated word (deterministic,
// good enough to exercise the batch/decode code paths).
int32_t llama_tokenize(const llama_vocab*, const char* text, int32_t text_len,
                       llama_token* tokens, int32_t n_tokens_max,
                       bool /*add_special*/, bool /*parse_special*/) {
    std::string s(text, text_len);
    std::vector<llama_token> toks;
    size_t i = 0;
    while (i < s.size()) {
        while (i < s.size() && isspace((unsigned char)s[i])) i++;
        size_t start = i;
        while (i < s.size() && !isspace((unsigned char)s[i])) i++;
        if (i > start) {
            // Fake token id = hash of the word, kept small & positive
            std::string word = s.substr(start, i - start);
            int32_t tok = (int32_t)(std::hash<std::string>{}(word) % 50000) + 100;
            toks.push_back(tok);
        }
    }
    if ((int32_t)toks.size() > n_tokens_max) return -(int32_t)toks.size();
    for (size_t k = 0; k < toks.size(); ++k) tokens[k] = toks[k];
    return (int32_t)toks.size();
}

static std::map<llama_token, std::string> g_fake_vocab_rev;

int32_t llama_token_to_piece(const llama_vocab*, llama_token token,
                             char* buf, int32_t length, int32_t, bool) {
    auto it = g_fake_vocab_rev.find(token);
    std::string piece = (it != g_fake_vocab_rev.end()) ? it->second : ("tok" + std::to_string(token));
    piece = " " + piece;
    if ((int32_t)piece.size() > length) return -(int32_t)piece.size();
    memcpy(buf, piece.data(), piece.size());
    return (int32_t)piece.size();
}

bool llama_vocab_is_eog(const llama_vocab*, llama_token token) {
    return token == 999999;  // never naturally generated by our fake sampler below
}

llama_batch llama_batch_init(int32_t n_tokens, int32_t /*embd*/, int32_t n_seq_max) {
    llama_batch b{};
    b.n_tokens = 0;
    b.token    = new llama_token[n_tokens];
    b.embd     = nullptr;
    b.pos      = new llama_pos[n_tokens];
    b.n_seq_id = new int32_t[n_tokens];
    b.seq_id   = new llama_seq_id*[n_tokens];
    for (int i = 0; i < n_tokens; ++i) b.seq_id[i] = new llama_seq_id[n_seq_max];
    b.logits   = new int8_t[n_tokens];
    return b;
}
void llama_batch_free(llama_batch batch) {
    delete[] batch.token;
    delete[] batch.pos;
    delete[] batch.n_seq_id;
    for (int i = 0; i < batch.n_tokens; ++i) delete[] batch.seq_id[i];
    delete[] batch.seq_id;
    delete[] batch.logits;
}

static int g_decode_call_count = 0;
static llama_token g_last_decoded_token = 0;

int32_t llama_decode(llama_context* ctx, llama_batch batch) {
    g_decode_call_count++;
    for (int i = 0; i < batch.n_tokens; ++i)
        ctx->kv_tokens.push_back(batch.token[i]);
    if (batch.n_tokens > 0) g_last_decoded_token = batch.token[batch.n_tokens - 1];
    return 0;  // success
}

uint32_t llama_n_ctx(const llama_context* ctx) { return ctx->n_ctx; }

void llama_kv_cache_seq_rm(llama_context* ctx, llama_seq_id, llama_pos p0, llama_pos p1) {
    printf("[stub] kv_cache_seq_rm(p0=%d, p1=%d) — kv had %zu tokens\n",
           p0, p1, ctx->kv_tokens.size());
    if (p1 < 0) {
        if ((size_t)p0 < ctx->kv_tokens.size())
            ctx->kv_tokens.resize(p0);
        else
            ctx->kv_tokens.clear();  // p0==0 && p1==-1 means "clear everything"
    }
}

llama_sampler_chain_params llama_sampler_chain_default_params() { return {false}; }

llama_sampler* llama_sampler_chain_init(llama_sampler_chain_params) {
    auto* s = new llama_sampler{};
    s->is_chain = true;
    return s;
}
void llama_sampler_chain_add(llama_sampler* chain, llama_sampler* smpl) {
    chain->chain.push_back(smpl);
}
llama_sampler* llama_sampler_init_temp(float t) {
    auto* s = new llama_sampler{};
    s->kind = 1; s->temp = t;
    return s;
}
llama_sampler* llama_sampler_init_dist(uint32_t) {
    auto* s = new llama_sampler{};
    s->kind = 2;
    return s;
}

static int g_sample_counter = 0;

llama_token llama_sampler_sample(llama_sampler*, llama_context*, int32_t) {
    // Deterministic fake generation: produce a few tokens then EOG.
    g_sample_counter++;
    if (g_sample_counter > 5) { g_sample_counter = 0; return 999999; }
    llama_token t = 200 + g_sample_counter;
    g_fake_vocab_rev[t] = "word" + std::to_string(g_sample_counter);
    return t;
}
void llama_sampler_accept(llama_sampler*, llama_token) {}

void llama_sampler_free(llama_sampler* chain) {
    for (auto* s : chain->chain) delete s;
    delete chain;
}

} // extern "C"
